id: P42A6FE87
initial_creation_type: input
source_metadata:
  title: Jatsön Nyingpo Series
  language: en
  description: 'Texts by and about the treasure-revealer Jatsön Nyingpo (’ja’ tshon
    snying po, 1585–1656), whose revelations include the famous Könchok Chidü (dkon
    mchog spyi ’dus) or ''Embodiment of the Three Jewels'':'
  volume:
    a1399b9a80f24db2b07da66ed16c3738:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Guidebooks
    a15f343f62a442d2be650c529e574617:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Offering
    35d77b56abaf43ce934e16abee963b9a:
      title: Prayer to Rigdzin Jatsön Nyingpo
      parent: Prayers
created_at: '2022-03-01T00:00:06.151540'
last_modified_at: '2022-03-01T00:00:06.151546'
